[SEDONA-3] Update project layout, add A11Y
methcm/Sedona pull request #6
Opened 2021-10-31 20:12 UTC by methcm

[SEDONA-3] Update project layout, add A11Y

----

#### 🚀 Я имплементировал фичу:

Добавил верстку форм, добавил картинки в код, загрузил логотип.

---
#### 🤔 Как я это делал:

2021-11-01 18:31 UTC, NicolaHorbach requested changes

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +        <img src="images/background-photo.jpg" width="1200" height="217" alt="">
удали. будет через цсс
файл картинки пусть остается

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +              <label for="filter-swimingpool">бассейн</label>
Когда инпут и лейбл лежат рядом, их можно писать вот так. Работает так же, как и через связку for + id
При клике на текст оно будет переводить курсор на поле. Переделай так все label + input
```suggestion
             <label>
               <input type="checkbox" name="swimingpool" checked>
               <span>бассейн</span>
             </label>
```

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +              <label for="filter-parking">парковка</label>
Переделай

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +              <label for="filter-wi-fi">wi-fi</label>
Переделай

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +              <label for="filter-hotel">Гостиница</label>
Переделай

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +              <label for="filter-motel">Мотель</label>
Переделай

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +              <label for="filter-apartments">апартаменты</label>
Переделай

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
>                  <a href="#">
aria-label добавь

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
>                  <a href="#">
aria-label

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +                  <button type="submit">подробнее</button>
Это не форма, какой type="submit"
такой тип используется в формах. Верни как было и добавь ссылке aria-label

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +                  <button type="submit">забронировать</button>
Такая же правка, как и выше

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +                <img src="icons/shape.svg" width="17" height="18" alt="">
нельзя делать пустой альт
Это иконки, которые не нужны пользователю с читалкой, потом поставь вместо alt="" aria-hidden="true" и почитай про этот атрибут
Исправь на всех звездочках в проекте

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +                <img src="icons/shape.svg" width="17" height="18" alt="">
Каким образом звезды и текст будут отделяться от ссылок? Переделай структуру. Ее можно сделать лучше

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +                  <button type="submit">забронировать</button>
Верни как было и добавь альты

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +                <p>рейтинг: 8,9</p>
```suggestion
                <div>
                  <div>
                    <img src="icons/shape.svg" width="17" height="18" alt="">
                    <img src="icons/shape.svg" width="17" height="18" alt="">
                    <img src="icons/shape.svg" width="17" height="18" alt="">
                  </div>
                  <p>рейтинг: 8,9</p>
                </div>
```

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +                  <button type="submit">забронировать</button>
Верни как было и добавь альты

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +                <p>рейтинг: 9,2</p>
исправь по правке выше

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +            <img src="icons/twitter.svg" width="16,98" height="15,01">
дай картинке нормальные размеры 
без запятых и всего говна 
округляй по матиматическим правилам

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +        <img src="icons/logo-htmlacademy.svg" width="115" height="41" alt="">
альт пустой не должен быть, исправь

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +              <img src="icons/eat.svg" width="75" height="70" alt="еда">
Это иконка, у нее нету альта
поменяй на aria-hidden="true"

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +              <img src="icons/souvenir.svg" width="64" height="77" alt="сувениры">
исправь как выше

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +            <img src="images/bridge.jpg" width="800" height="256" alt="мост">
исправь как выше

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +            <input id="appointment-date" type="date" name="date" placeholder="24 апреля 2017 года">
Переделай как в первой форме

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +            <input id="appointment-date" type="date" name="date" placeholder="4 июля 2017 года">
Переделай как в первой форме

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +            <button type="button">-</button>
Переделай как в первой форме
(в лейбл оберни все)

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +            <button type="button">-</button>
Переделай как в первой форме
(в лейбл оберни все)

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +           <img src="icons/twitter.svg" width="17" height="15">
иконкам дай aria-hidden="true"

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +           <img src="icons/twitter.svg" width="17" height="15">
отступ 1 пробел, а не 1 таб

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +            <img src="icons/fb.svg" width="12" height="22">
иконкам дай aria-hidden="true"

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +            <img src="icons/youtube.svg" width="20" height="16">
иконкам дай aria-hidden="true"

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +        <img src="icons/logo-htmlacademy.svg" width="115" height="41">
альт

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +            <button type="button">-</button>
текст кнопок оберни в текстовый тег

2021-11-01 18:31 UTC, NicolaHorbach commented on source/index.html
> +            <button type="button">-</button>
текст кнопок оберни в текстовый тег

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +        <img src="icons/logo.svg" width="138" height="70">
альт

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +            <img src="icons/twitter.svg" width="16,98" height="15,01">
иконкам дай aria-hidden="true"

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +            <img src="icons/fb.svg" width="12" height="22">
иконкам дай aria-hidden="true"

2021-11-01 18:31 UTC, NicolaHorbach commented on source/hotels.html
> +            <img src="icons/youtube.svg" width="20" height="16">
иконкам дай aria-hidden="true"

2021-11-01 18:37 UTC, NicolaHorbach commented on source/hotels.html
> +                <p>рейтинг: 8,9</p>
И вынеси их из блока информации о гостинниц
<img width="1016" alt="Снимок экрана 2021-11-01 в 20 36 20" src="https://user-images.githubusercontent.com/44953799/139723294-040d5c37-a7d6-47fa-8024-9c12a8eb8fca.png">
е
Вся карточка пускай выглядит вот так

2021-11-01 19:02 UTC, NicolaHorbach commented on source/hotels.html
>        <ul>
В ссылках навигации не добавил aria-label

2021-11-01 19:03 UTC, NicolaHorbach requested changes

2021-11-01 19:03 UTC, NicolaHorbach commented on source/index.html
>          <li>
добавь aria-label в ссылки навигации

2021-11-02 11:52 UTC, methcm commented on source/hotels.html
> +            <img src="icons/twitter.svg" width="16,98" height="15,01">
иконкам самим aria-hidden="true"??? или ссылкам, вместо aria-label??

2021-11-02 12:00 UTC, methcm commented on source/index.html
> +            <img src="images/bridge.jpg" width="800" height="256" alt="мост">
почему тут не должно быть alt? это же jpeg картинка
на которой мост дьявола изображен, вот я и поставил alt="мост"

2021-11-02 12:18 UTC, methcm commented on source/index.html
> +            <button type="button">-</button>
<span>+</span>
или 
<p>+</p>

2021-11-02 12:18 UTC, methcm commented on source/index.html
> +            <button type="button">-</button>
span + /span
или
p + /p 
???

2021-11-02 12:20 UTC, NicolaHorbach commented on source/hotels.html
> +            <img src="icons/twitter.svg" width="16,98" height="15,01">
Самим иконкам, каждой)

2021-11-02 12:21 UTC, NicolaHorbach commented on source/index.html
> +            <img src="images/bridge.jpg" width="800" height="256" alt="мост">
Сори. Лишнее. Молодец, что заметил

2021-11-02 12:22 UTC, NicolaHorbach commented on source/index.html
> +            <button type="button">-</button>
давай лучше тут пока оставим без дополнительного тега на текст. Если будет нужно - добавим

2021-11-02 12:22 UTC, NicolaHorbach commented on source/index.html
> +            <button type="button">-</button>
Просто переделай обернув в label, вместе с кнопками

2021-11-02 12:39 UTC, methcm commented on source/hotels.html
> +        <img src="images/background-photo.jpg" width="1200" height="217" alt="">
что удалить???

2021-11-02 12:40 UTC, methcm commented on source/hotels.html
>                  <a href="#">
aria-label???
в ссылках в обертке div?? 
a href="#" aria-label??? 
просто не точно указал, не понимаю

2021-11-02 12:41 UTC, methcm commented on source/hotels.html
>                  <a href="#">
если в ссылки перед спаном амара ресорт, то какой в ссылках должен быть aria-label? 
что-то типо такого: aria-label перейти на страницу amara resort??

2021-11-02 12:41 UTC, NicolaHorbach commented on source/hotels.html
> +        <img src="images/background-photo.jpg" width="1200" height="217" alt="">
правки тут кидаются на строку. Это правка на 43 строку. удали ее. Это не контентная картинка

2021-11-02 12:42 UTC, NicolaHorbach commented on source/hotels.html
>                  <a href="#">
всмысле не точно? Здесь указана конкретная строка
последняя строка (118)
А куда тут еще можно кинуть aria-label?

2021-11-02 12:43 UTC, NicolaHorbach commented on source/hotels.html
>                  <a href="#">
да, что-то типа такого
НО 
ЛЕЙБЛ ДОЛЖЕН БЫТЬ НА ВСЕХ ССЫЛАХ БЕЗ ИСКЛЮЧЕНИЯ

если я что-то не отметил , то исправь сам

2021-11-02 13:56 UTC, NicolaHorbach requested changes

2021-11-02 13:56 UTC, NicolaHorbach commented on source/hotels.html
>                </div>
структура ок, но поставил не там. 
У тебя этот блок получается внутри блока информации
Вынеси за закрывающий див после ссылок

2021-11-02 13:56 UTC, NicolaHorbach commented on source/hotels.html
>                </div>
Сейчас он на 148 строке

2021-11-02 13:56 UTC, NicolaHorbach commented on source/hotels.html
> +                </div>
тут тоже исправь

2021-11-02 13:56 UTC, NicolaHorbach commented on source/hotels.html
> +                </div>
и тут исправь

2021-11-02 13:56 UTC, NicolaHorbach commented on source/index.html
> +            </label>
текст "взрослые:" вынеси в спан

2021-11-02 13:56 UTC, NicolaHorbach commented on source/index.html
> +            <label>дети:
тоже вынеси в спан

2021-11-02 13:58 UTC, NicolaHorbach commented on source/hotels.html
>                </div>
```
<картинка>
<div>
  информация
</div>
<div>
 рейтинг
</div>
```

2021-11-02 14:16 UTC, methcm commented on source/hotels.html
>                </div>
тут не понимаю

2021-11-02 15:10 UTC, NicolaHorbach requested changes

2021-11-02 15:10 UTC, NicolaHorbach commented on source/hotels.html
> +          <a href="#" aria-label="параметры по цене">
параметры по цене что?

"Сортировать параметры по цене"
В остальных ссылках то же самое

2021-11-02 15:10 UTC, NicolaHorbach commented on source/hotels.html
> +          <a href="#" aria-label="парметры по типу">
исправь

2021-11-02 15:10 UTC, NicolaHorbach commented on source/hotels.html
> +          <a href="#" aria-label="параметры по рейтингу">
исправь

2021-11-02 15:10 UTC, NicolaHorbach commented on source/hotels.html
>              <div>
Этот див между article и img и его закрывающий див надо убрать

2021-11-02 15:10 UTC, NicolaHorbach commented on source/hotels.html
>              <div>
Этот див между article и img и его закрывающий див надо убрать

2021-11-02 15:10 UTC, NicolaHorbach commented on source/hotels.html
>              <div>
Этот див между article и img и его закрывающий див надо убрать
Табуляцию поправить не забудь во всех местах

2021-11-02 15:35 UTC, merged