[SEDONA-6] Create styles for header
methcm/Sedona pull request #9
Opened 2021-11-16 21:38 UTC by methcm

[SEDONA-6] Create styles for header

----

#### 🚀 Я имплементировал фичу:

Написал стили для шапки

2021-11-18 17:22 UTC, NicolaHorbach requested changes

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/base.scss
> +
Это не нужно, у тебя отдельные файлы. Комментарии нужны, если файл огромный и ты отделяешь блоки

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/base.scss
> +  text-transform: uppercase;
Не уверен, что это нужно. Лучше отдельно прописывать апперкейс в нужных местах

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/base.scss
> +  background-color:#FFFFFF;
пробел перед # добавь

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/base.scss
> +body {
ты добавил класс на тег боди, значит, стилизуй по классу

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/base.scss
> +
Зачем оставил, если свойства комментом?

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/base.scss
> +  align-content: start;
нет. Гриды - это слишком рано. Переделай.

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/base.scss
> +  align-content: start;
И ты разбил стилизацию блока page-body на 2 куска. 1 в начале, 1 тут. Собери их вместе.

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/logo.scss
> +  outline-offset: -5px;
окей, ты пытаешься разделять свойства, но делаешь э о не совсем правильно. 
Записывай свойства следующим образом:
Позиционирование, 
Дисплеи, настройки дисплеев,
Размеры,
Отступы,
Оформление, 
Текста

Пропускай строку только если группы, описанные выше, большие. Сейчас пропуск строки не нужен

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/navigation.scss
> +  margin-bottom: 60px;
запиши в нужном порядке

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/navigation.scss
> +  margin: 0;
навигация - это не список, тут list-style: none; не нужен

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/navigation.scss
> +  padding: 0;
Вынеси в нормалайз для тега ul

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/navigation.scss
> +
пустая строка

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/page-header.scss
> +  outline-offset: -5px;
запиши в правильной последовательности

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/page-header.scss
> +  color: #000000;
ты эти свойства написал в стилизации body , зачем дублируешь? Они наследуются

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/modules/page-header.scss
> +  outline-offset: -5px;
и дропни пустую строку

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/style.scss
> +@import "source/css/style.css";
ударь себя по рукам
нахера тут импорт цссника?

2021-11-18 17:22 UTC, NicolaHorbach commented on source/styles/style.scss
> +@import "modules/page-header.scss";
2 раза импорт хедера

2021-11-19 13:56 UTC, methcm commented on source/styles/modules/base.scss
> +  text-transform: uppercase;
просто весь сайт на писан uppercase'ОМ
вот и подумал в глобальные стили записать.

2021-11-19 14:01 UTC, methcm commented on source/styles/modules/base.scss
> +  align-content: start;
Это у меня была такая идея
display: grid; - для все страницы
g-t-r: min 1fr min;
чтоб шапка и футер заняли минимум контента, а все остальное сколько нужно, это у академии на курсах позаимствовал идею, как переделать? могу пока просто убрать, все равно ничего не поменяется =)

2021-11-19 14:02 UTC, methcm commented on source/styles/modules/logo.scss
> +  outline-offset: -5px;
вот это хорошо подметил, я все думал о правильном расставлении свойств
ибо чтоб они везде были одинаковы и шли в определенном порядке, сейчас  переделаю)

2021-11-19 14:09 UTC, methcm commented on source/styles/modules/navigation.scss
> +  padding: 0;
просто в нормалайз вписать ?? я просто не знал, что в нормалайз можно самому что-то добавить и чтоб это глобально применялось, спасибо, сделаю)
ul {
  list-style: none;
  padding: 0;
}

2021-11-19 16:09 UTC, NicolaHorbach approved these changes

2021-11-19 16:09 UTC, merged